name: Image Run
description:  run a shell script within a docker image
author: fduser1

inputs:
  image:
    description: docker image
  run:
    description: script to run
  shell:
    description: shell within image to run script
    default: sh
  options:
    description: additional options to pass to docker run command
    default: ''

runs:
  using: composite
  steps:
    - shell: bash
      env:
        _ENVS: ${{ toJSON(env) }}
        _INPUT_RUN: ${{ inputs.run }}
      run: |
        env_opts=$(echo "$(
          echo "$_ENVS" | grep -E "^\\s+\"" | awk -F"\"" '{print $2}';
          env | awk -F= '{print $1}' | grep -E "^(INPUT_.*|GITHUB_.*|RUNNER_(ARCH|ENVIRONMENT|NAME|OS|TEMP|TOOL_CACHE|WORKSPACE))$" | grep -v GITHUB_ACTION_PATH;
          env | awk -F= '{print $1}' | grep -Ei "^(http|https|no|ftp|rsync|npm_config|npm_config_https)_proxy$";
        )" | awk 'BEGIN{ORS=" "} {print "-e " $0;}')
        env_opts="$env_opts -e GITHUB_ACTIONS=true -e CI=true"

        vol_opts="-v /var/run/docker.sock:/var/run/docker.sock \
                  -v ${{runner.temp}}/_github_home:/github/home \
                  -v ${{runner.temp}}/_github_workflow:/github/workflow \
                  -v ${{runner.temp}}/_runner_file_commands:/github/file_commands \
                  -v ${{github.workspace}}:/github/workspace \
                  "

        name="image_run_$(date +%s%N | cut -b1-13)"

        docker run --name $name --workdir /github/workspace --rm $env_opts --entrypoint "${{ inputs.shell }}" $vol_opts \
                    ${{ inputs.options }} ${{ inputs.image }} -c "$_INPUT_RUN"
